#!/usr/bin/env bash
#A bash script that transfers a file
#from our client to a server.
#The script must accept 4 parameters.

if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

scp_options="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
scp -i "$path_to_ssh_key" $scp_options "$path_to_file" "$username@ip:~/"
fi
