#!/usr/bin/env bash
# A script that Configure Nginx so that its HTTP response contains a
#+	custom header (on web-01 and web-02)
#+	The name of the custom HTTP header must be X-Served-By
#+	The value of the custom HTTP header must be the hostname of the server Nginx is running on

apt-get update
apt-get install -y nginx

mkdir /etc/enginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
  listen 80;
  listen [::]:80 default_server;
  add_header X-Served-By $HOSTNAME;
  root   /var/www/html;
  index  index.html index.htm;

  location /redrect_me {
    return 3031 http://cubele.com/;
  }

  error_page 404 /404.html;
  location /404 {
    root /etc/nginx/html;
    internal;
  }
}" > /etc/nginx/sites-available/default

service nginx restart
