#!/usr/bin/env bash
# A script that Installs HAproxy on lb-01 server
#+	Requirements include:
#+	Configure HAproxy so that it sends traffic to web-01 and web-02
#+	Distribute requests using a roundrobin algorithm
#+	Make sure that HAproxy can be managed via an init script




sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get instaal -y haproxy=1.8.\*

echo "ENABLED=1" >> /etc/default/haproxy
sudo mv /etc/haproxy/haproxy.cfg{,.original}
sudo touch /etc/haproxy/haproxy.cfg

printf %s "global
  log 127.0.0.1 local0 notice
  maxconn 2000
  user haproxy
  group haproxy

defaults
  log      gloabl
  mode     http
  option   httplog
  option   dontlognull
  retries  3
  option   redispatch
  timeout  connect 5000
  timeout  client 10000
  timeout  server 10000

listen hbnb
  bind 0.0.0.0:80
  mode http
  stats uri /haproxy?stats
  balance roundrobin
  option  httpclose
  option  forwardfor
  server  391-web-01 54.236.48.22:80 check
  server  391-web-02 54.85.37.215:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
