#!/bin/env bash
#A script that  generates a MySQL dump and creates
#	a compressed archive out of it.

# Check if the password argument is provided
if [[ $# -eq 0 ]]; then
  exit 1
fi


password=$1


date=$(date +"%d-%m-%Y")

dump_file="backup.sql"
archive_file="$date.tar.gz"
mysqldump -u root -p$password --all-databases > $dump_file
tar -czvf $archive_file $dump_file

rm $dump_file

