#!/usr/bin/env bash
#A script that configures the container to fit the requirements below:
#	nginx must be running as nginx user
#	nginx must be listening on all active IPs on port 8080
#	Can not use apt-get remove
sudo pkill apache2
sleep 2
sudo chmod 777 /etc/nginx/nginx.conf

#Update nginx configuration to listen on all active IPs on port 8080
sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default

sudo -u nginx start
