#!/usr/bin/env bash
# configures Nginx to serve the route /airbnb-onepage/ from AirBnB_clone_v2.

server {
	#listen on port 80
	listen 80;
	listen [::]:80 default_server ipv6only=on;

	#server IP use as Domain name
	server_name 54.236.48.22;

	add_header X-served-By 391805-web-01;

	#serve /airbnb-onepage/ route
	location = /airbnb-onepage/ {
		proxy_pass http://127.0.0.1:5000/airbnb-onepage/;
	}

	#404 error page
	error_page 404 /404.html;
	location /404 {
		root /var/www/html;
		internal;
	}
}
