#!/usr/bin/env bash
# Nginx route /api/ points to a Gunicorn instance.

server {
        listen 80;
        listen [::]:80;

        server_name 54.236.48.22;

        #Custom HTTP response header
        add_header X-Served-By 391805-web-01;


        #Serve /airbnb-onepage/ route on AirBnB_clone_v3
        location = /airbnb-onepage/ {
                proxy_pass http://127.0.0.1:5000/airbnb-onepage/;
        }


        #Serve /airbnb-dynamic/number_odd_or_even/ route on AirBnB_clone_v3
        location /airbnb-dynamic/number_odd_or_even/(\d+)$ {
#               try_files $uri $uri/ =404;
                proxy_pass http://127.0.0.1:5001/number_odd_or_even/$1;
        }

        #Serve API on AIrBnB_clone_v3
        location /api {
                proxy_pass http://127.0.0.1:5002/api;
        }

        #error page
        error_page 404 /404.html;
        location /404 {
                root /var/www/html;
                internal;
        }
}
